export const teamName = "spotifour";

export const groupGithubUrl = "https://github.com/spotifour";
export const repoGithubUrl = "https://github.com/spotifour/spotifour";
export const DTNUrl = "https://www.dtn.com.vn/";

export const teamMembers = [
  {
    name: "Dang Thai Hoang",
    img: "ThaiHoang.jpg",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    name: "Le Trinh Quoc Huynh",
    img: "QuocHuynh.jpeg",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    name: "Vu Tuan Linh",
    img: "TuanLinh.png",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
  {
    name: "Dau Hoang Minh",
    img: "HoangMinh.jpeg",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
  },
];

export const ITWorkQnAs = [
  {
    question: "Introduction",
    answer: [
      "The IT professional we interviewed is Mr. Hans; his full name is Phung Van Hanh. He is the CTO (Chief Technology Officer) of DTN Software Solutions, an IT company specializing in providing eCommerce development solutions for customers worldwide, mainly in Europe. His company focuses on building e-commerce websites using Magento, an e-commerce platform written in PHP programming language and was acquired by Adobe in May 2018.",
    ],
  },
  {
    question: "What kind of work is done by the IT professional?",
    answer: [
      "His company provides eCommerce solutions for customers and builds an ecosystem around Magento, an open-source platform for eCommerce websites. In addition to developing websites, they also create mobile apps, integrate online customer channels with other systems like ERP (Enterprise Resource Planning), POS (Point Of Sales), and support customers on marketing activities.",
      "Therefore, as a Chief Technology Officer of a technological company, he handles those major areas:",
      "- Develop company technical stacks, keep them up to date with technology changes",
      "- Develop employees’ technical skills",
      "- Deploys, maintains business applications, services, and infrastructure",
      "- Monitors, optimizes, troubleshoots the performance of applications, services and infrastructure",
      "- Do technical lead, write boilerplate code, review code",
      "Besides technical tasks, he also participates in general company management activities like interviewing candidates, reviewing employees annually, and building a company learning culture.",
    ],
  },
  {
    question:
      "What kinds of people does the IT professional interact with? Are they other IT professionals? Clients? Investors? The general public?",
    answer: [
      "He interacts with a variety of people at work. Because he is a tech lead, he primarily interacts with the developers. He helps them come up with solutions for their problems, reviews their code, and trains them. Besides that, he also works with the project management and quality assurance teams to discuss projects timeline, working quality, human resources, etc. Last but not least, he also joins with the BA (Business Analysis) team to work directly with the clients in clarifying their business requirements, so his company can provide appropriate solutions for their needs.",
      "In terms of his interaction with other IT professionals, he likes watching videos and reading their blog posts to acquire new skills. Moreover, he also wants to share his knowledge with others in the same ways. Therefore, he has his personal blog for this, where he posts things about Magento, website technologies and DevOps. To attract more people to see his blog, he usually shares posts on programming groups on Facebook or Twitter. He finds that Twitter is a pretty good place where IT professionals can learn new things from others, keep them up to date with technology changes in their fields, as well as share their knowledge.",
      "His role does not require him to contact the general public. His company only provides eCommerce solutions for clients, and those customers are the people who are responsible for managing their web as well as communicating with users - the general public.",
    ],
  },
  {
    question: "Where do the IT professionals spend most of their time?",
    answer: [
      "He said that he spent the most time reviewing code and setting up a working environment at the company's office. He always prioritizes achieving high coding quality to deliver the best product quality to customers. He takes responsibility for many projects at a time, so reviewing code is the most critical and time-consuming part of his daily work. It usually takes him about 1 - 2 hours to do this daily.",
      "His other tasks include setting up the working environment for each project, deploying websites, providing any supplies if needed, ensuring the team members have everything they need. Every computer comes with an on-ear headphone to keep users from being distracted by outside noises. Each employee also has a personal space where they can store personal items such as writing pads, catalog envelopes, self-stick notes, and so on. Snacks, tea, and coffee are also available on two tables for employees to use whenever they are tired or hungry. Thanks to those working conditions, all technical employees can focus on coding, and not have to worry about other problems that might distract them.",
      "For him, the office is a second home where he eats, sometimes even cooks, does exercises, and communicates with others on a daily basis. Due to the Covid-19 pandemic, there were times that he and his co-workers were not allowed to go to the offices, so he had to spend most of his time working alone at home. However, he still prefers to work in the office rather than at home because meeting offline improves working efficiency and employee relationships.",
    ],
  },
  {
    question: "What aspect of their position is most challenging?",
    answer: [
      "In his opinion, the most challenging aspect is training people. Leading people means dealing with different personalities and abilities. He always has to find and understand how to develop an employee to their best version and improve their work skills to add more value to the company in the market. Technically, he thinks that there is no best way to work for everyone. Some may enjoy working with Frontend technologies like Javascript, CSS, React, ... or some may find Backend or DevOps interesting. He identifies their strengths and gives them suggestions, training sessions, or courses so they can develop themselves most effectively.",
      "In addition, interacting with clients is another aspect he finds challenging. He must fill the gap between business people and the technical team because they usually have misunderstandings. Sometimes, the technical team do not understand clearly the requirement of customers and As a technical person, he also needs to understand how customer business works, not only online eCommerce, but also many problems around it, like marketing tools, order management process, stock management, SEO, or any other system.",
    ],
  },
];

export const ITTechs = [
  {
    technology: "Web Development",
    image: "Web.png",
    description: {
      "What does it do?": [
        "Web development is the process of creating a website that is available and can be accessed via the Internet. This field varies from building just a single static page to enterprise applications that have millions of users. It can be divided into many sub-fields, including web engineering, web design, web server, network security, etc. Many programming languages and platforms can be used in the process of making a website, depending on the scale, resources, and purposes of the project.",
        "Web development has experienced incredible improvement over the last decade. It is an essential part of any industry at the moment. For example, business owners can now open an e-commerce website to raise their sales. In large corporations, websites are used to extract, visualize, and analyze data to help them come up with better business solutions. In addition, using websites is an excellent resource for people to consume information and even create and share their content in the form of blogs or social media. Modern websites provide users with a high-quality user interface and dynamic content, which means that what the website displays will change according to users' input. Moreover, with the help of databases, all of the users' data can be saved for their future sessions. Companies can also utilize that information to develop strategies to help keep old customers and attract new ones. Furthermore, everyone can have their online presence on the Internet; they can upload, share, and even sell any digital product like images or videos on the Internet. Humans can contact each other by chatting or video calls by using social platforms.",
        "Web development will undoubtedly keep growing in the next few years. The number of new back-ends and front-ends frameworks for building websites will continue to rise, allowing IT specialists to develop, maintain, and deploy websites most efficiently. As a result, websites will see a massive improvement in performance and complexity. More websites will have 3D graphical interfaces, providing users with a more realistic and interactive experience. This can even help simulate real-life situations for science research, like autonomous cars or even astronomy exploration. Artificial intelligence and machine learning technologies can also be applied to e-commerce and entertainment websites for suggesting recommendations for users based on their historical use of the website. Website owners can use chatbots on their sites to resolve any questions from the customers without the need for virtual assistants. With the help of blockchain, all websites will have much better security and privacy when people can own their digital content and not rely on any network of big corporations.",
        "Those breakthroughs of web development are the results of many reasons. The first and most apparent cause is the thrive of new advanced fields in IT, including artificial intelligence, machine learning and blockchain. These fields can be implemented in order to make websites have a higher quality in every aspect ranging from user experience to network privacy. The second reason is that websites have to be continuously improved to meet people's requirements, from day-to-day activities like shopping or connecting to scientific research. The final reason is the massive improvement of electronic devices. More and more types of phones, tablets and desktops with different brands, designs and operating systems are available in the market. As a result, organizations have to develop sites that can run efficiently across all of those devices to continue increasing their revenue."
      ],
      "What is the likely impact?": [
        "Web development has revolutionized many industries in our lives, and it will assuredly continue doing so in the future. For example, in education, there will be more and more online course websites that can support students from any level to learn any kind of subject they like, from art to science. Moreover, those websites will provide users with experiential learning, when they can practice the skills they just learnt right on the website. This can lead to the steady replacement of online learning to face-face teaching. With the help of AI/ML, entertainment platforms like social media, streaming or gaming will provide users with a much more engaging experience. The number of e-commerce websites will also rise considerably to help business owners increase revenue and allow customers to make online orders and payments easily.",
        "Web development changes many aspects of human habits and improves our lives in many ways. Online businesses, courses and entertainment platforms are constantly being built, maintained, and enhanced to help us have easier, happier, and productive lives.",
        "People across all industries are affected by web development. The IT industry always has to evolve to deliver high-quality websites for other industries. Therefore, people working in this field must always stay up to date with the latest technologies in order to come up with websites that suit users' needs. The development of website technologies can be considered a win-win case for both business owners and customers; business owners can dramatically attract more users and increase their revenue while customers will have a better experience when using the websites.",
        "Web development helps create many IT jobs, ranging from developers, designers to business analysts or testers. The US Department of Labor projects that there will be a 13% growth of jobs for Web Developers and Digital Designers between 2020-2030. There have not been many concerns about web development replacing existing jobs. However, the rise of online learning and shopping can have a negative impact on teachers and owners of traditional stores."
      ],
      "How will this affect me?": [
        "As a student of RMIT, integrating myself with websites is an essential part of my daily routine. I use websites for many purposes, from supporting my study to entertaining. The advancement of website technologies allows me to access and consume the contents of websites much faster and simpler than at the moment. As a result, it will be much more efficient whenever we need to research for my university study. Moreover, with many high-quality and practical online course websites available online, I can study any subjects and new skills that we like without the help of instructors. I also use a lot of entertainment platforms. The advancement of AI/ML and 3D Graphics in websites will bring me a much better time enjoying online games, music, and movies.",
        "Web development has changed my life over the past decades. For example, online payment on websites was unavailable in older days, but now I can transfer money quickly with only a few clicks. Looking into the future, with the rise of blockchain, I can use cryptocurrencies to deal with transactions on websites, which is much more secure than bank transfers. In addition, since website contents are getting more and more privacy and focusing more on individuals instead of communities, I can also create, share and even sell content on the Internet without any issues related to authorization.",
        "My friends will most likely take advantage of the advancement of websites to enhance many parts of their lives, just like me. They will have a better experience while studying, relaxing, shopping or even creating and sharing content on websites. My family members mostly use websites to update news, and they are not very familiar with complex technologies. Therefore, since websites are being designed to become easier and easier to navigate, my family members will benefit greatly."
      ]
    },
  },
  {
    technology: "Artificial Intelligence",
    image: "Ai.png",
    description: {
      "What does it do?": [
        "Artificial intelligence (AI) is a term that refers to the ability of machines to do tasks generally associated with human intellect, such as learning, adapting, self-correction, etc. Machine learning is a subfield of artificial intelligence that allows software programs to evolve over time, improving prediction accuracy based on gathered data and, as a result, adapting their behavior to fit the surrounding environment.",
        "Artificial intelligence is an up-and-coming field with a wide range of applications. Although artificial intelligence has only been discovered and studied since the twentieth century, there have been several significant advancements in this technology in different fields.",
        "- In the field of robotics, an AI-enabled robot right now can detect any obstacles in its route and plan an optimal way to get to the given location. These robots may be used to transport heavy equipment in warehouses and factories as well as clean public places. Those are the tasks that would usually necessitate the participation of so many persons.",
        "In the gaming industry, we have an exceptional artificial intelligence named AlphaGo, a computer created to play the board game Go. AlphaGo can comprehend a human's realistic manner of playing by analyzing data from matches with different amateurs and professionals. In 2016, it surprised everyone when defeating Go Champion Lee Sedol 4-1, marking a milestone in artificial intelligence development.",
        "- AI plays a crucial role in data analysis. Data analysts may employ AI to help them manage and analyze large databases. For example, they use Helixa, an AI program that provides insights into customer behavior with more accurate results. These services may be used by marketers to create more complete client profiles and better-targeted marketing campaigns.",
        "- AI also assists in the fields of science and research. 'Eve,' an AI-based robot, is an excellent example. It discovered a component of toothpaste that can treat Malaria, a deadly illness claiming many lives in the past.",
        "Big data and machine learning technologies may allow AI technology to advance further in the future. Big data is a broad term that refers to a variety of voluminous and high-speed digital information assets that cannot be handled with traditional methods. With the advancement of big data, there will be more amount of both structured and unstructured data for computers to evaluate at a faster rate. On the other hand, machine learning can assist in recognizing patterns in the data, categorizing it into various groups, and translating it into valuable insights.",
        "- In the field of social media, because of the enormous number of users, there is also a large amount of data generated every day. Social media companies use AI to track users' activity to know about customer behaviors and interests based on the posts they like or the videos they watch. AI can draw a picture of the target audience and build a solid framework for their customers, allowing businesses to make informed decisions. However, data management flaws still exist in several situations right now. In the future, the analytic technique will grow to be more precise, allowing social media companies to learn more about their customers and make appropriate changes.",
        "- In the healthcare sector, combining AI and big data would be beneficial in monitoring and revealing useful patterns among vast amounts of patient data, allowing doctors to plan appropriate check-ups and treatment schedules. For instance, Beth Israel is working on a mobile app that will collect data from millions of patients and aid clinicians in providing evidence-based care."
      ],
      "What is the likely impact?": [
        "Artificial intelligence is used in a wide range of industries, including business, science, manufacturing, transportation, etc. Therefore, its advancement has a significant impact on society.",
        "The positive impact of AI is the improvement in work efficiency. Humans sometimes make mistakes if they are distracted by the surrounding environment. Computers, on the other hand, are solely concerned with performing the tasks at hand. They have been trained to perform millions of calculations to finish tasks with excellent quality in less time. Furthermore, because AI can perform the task of many individuals, there will be a reduction in the number of employees, resulting in lower staffing costs.",
        "The major negative impact of AI is making some people lose their jobs. The most affected people are those who work in jobs that do not require them to be creative or solve ethical issues. Several jobs might be replaced by computers in the future:",
        "- Factory worker: most commodities have already been merchandised with AI, so there will only be one or two supervisors who control the machine.",
        "+ Proofreader: While editing takes a lot of time and effort, detecting grammatical errors and sentence structure can be done automatically with applications like Grammarly.",
        "+ Driver: We now have self-driving automobiles that go at a modest speed and are aware of the best route to take to reach their destination. As per the Los Angeles Times, self-driving trucks could replace 1.7 million American truckers in the next ten years.",
        "+ Security guards: With its high-definition camera, a security robot can easily investigate a building and determine the number of persons in a specific location. It also contains sensors that can detect any suspicious activities and transmit police notifications. AI has an 84 percent possibility of completely automating this industry in the future.",
      ],
      "How will this affect me?": [
        "Artificial intelligence appears in my daily life frequently to fulfill various functions. It improves the convenience and comfort of my life by allowing me to save time on regular duties.",
        "- When I wake up in the morning, I open my iPhone using Face ID. It is essentially an AI-based facial recognition feature that memorizes my face and records the image using 30.000 invisible dots. I just let the smartphone scan my face once, and my iPhone will unlock instantly the next time it sees my face.",
        "- When I have breakfast, I use the digital voice assistant of Apple named Siri – a form of virtual assistant driven by AI to manage my schedule. I can check the calendars for upcoming events, set alarms to remind me to complete several tasks, play the music I am interested in, etc.",
        "- When I have spare time, I usually watch Netflix. This streaming service also uses AI in its recommendation engine. It will suggest new movies to watch based on my previous viewing history, which has similar genres or actors I admire.",
        "My family members use AI applications in a variety of situations, but they are mostly unaware of it.",
        "- Whenever entering the company, my uncle marks his attendance by using a face-recognition machine, ensuring that he comes to the office on time.",
        "- My mom often buys products online, particularly on e-commerce sites such as Shopee, Tiki, and others. Artificial intelligence is also used by the corporations behind such platforms to handle data and recommend products to consumers, including discount programs and vouchers.",
        "- My sister usually transfers money and pays bills using her banking account. AI assists her in preventing unauthorized persons from making illegal purchases with her credit card."
      ]
    },
  },
  {
    technology: "Cloud Computing",
    image: "Cloud.png",
    description: {
      "What does it do?": [
        "In recent years, the rapid development of data storage and processing technologies, along with the success of the Internet, has made Cloud Computing more popular now than before. This paradigm provides the uses of computing services over the Internet – including databases, servers, storage, networking, analytics, software, and intelligence – with minimal management effort of the users. There are many benefits of Cloud Computing that make it attractive not only to businesses but also to individuals:",
        "- Cost: Cloud computing eliminates the upfront costs of purchasing hardware and software, as well as the costs of setting up and operating on-site data centers.",
        "- Global Scale: the ability to scale elastically provides suitable data.",
        "- Performance: Cloud computing services are delivered through a global network of secure data centers that are updated on a regular basis with the latest generation of fast and efficient computing gear.",
        "- Productivity: Cloud computing removes the need for unnecessary tasks so the IT team can concentrate on their work.",
        "- Reliability: cloud computing enables data backup, disaster recovery.",
        "In practice, cloud platform offers services that can be grouped into three different categories:",
        "- Software as a service (SaaS): a broad range of software offerings on the Cloud, and users can choose which one is suitable for their requirement. Clients can access a software application hosted by the cloud vendor on a pay-per-use basis. Example: Dropbox, Apple iCloud, Google Apps.",
        "- Platform as a Service (PaaS): provides a development platform on the Cloud. Clients can also rent servers, storage, database, software technologies for their works. Example: Google App Engine, Microsoft Window Azure.",
        "- Infrastructure as a service (IaaS): offering hardware-related services like servers, networks, and storage. Example: Google, IBM, Microsoft.",
        "For now, there are several common uses of Cloud Computing that businesses can take advantage of:",
        "- File storage: secure access and scalability to increase or decrease storage.",
        "- Big data analytic: data of current market trends, customers, sales performance, and many more.",
        "- Data backups: provides the assurance if users' data becomes compromised.",
        "- Software development: offers tools for continuous integration that make development and testing less complex, faster, and cheaper.",
        "In the near future, Cloud Computing will continue to be an essential target for businesses looking for cost efficiency and increased scalability. According to Forrester Research, the global Cloud infrastructure has gained 35 percent to $120 Billion in 2021 and will continue to take center stage in the development of technologies. Some of the features of Cloud Computing that are likely to be done soon are:",
        "- Going Serverless: a computing model in which cloud providers allocate resources on-demand and take care of the servers on behalf of their customers.",
        "- Automated Cloud Orchestration and Optimization: useful when managing a large quantity of data and the quality of interconnected services.",
        "- Internet of Things Along with Cloud Computing: The IoT field is also one of the leading technologies, and it requires machine-to-machine data transferring, communication, which Cloud Computing can easily help.",
        "- Modular software: modified software provides better security and is more flexible to use compared to traditional ones.",
        "In terms of state-of-the-art implementation of cloud computing, there are key technologies that are currently used for this paradigm:",
        "- Architecture Design of Data Center: The Data Center is a facility in which computer systems and associated components like servers, routers, telecommunication systems are used. The design and planning for this network architecture play a vital role as it will influence other factors like application performance, security, environment control, etc. A good design of a data center network should satisfy the following objectives:",
        "- Resiliency: The ability to recover after failures and ensure maximum uptime without compromising performance.",
        "- Scalability: The ability to broaden data storage and the number of servers.",
        "- Security: The ability to ensure data separation and prevent the access of unauthorized users.",
        "- Performance: the higher the processing speed, the more productive the work.",
        '- Distributed File System over Cloud: a file system that provides efficient, reliable access to data and allows users to modify it (copy, delete, rewrite, etc.). Each file system is partitioned into different parts called "chunks"; each can be stored on different remote machines to do the parallel execution. Google File System (GFS) and Hadoop Distributed system (HDFS) are two popular file systems built to support large files coming from different sources and various formats.',
        "- Distributed Applications over Cloud: these are software applications usually stored and executed on the cloud platform and run on multiple systems simultaneously. Unlike traditional applications, which focus on one dedicated system to achieve a task, these distributed systems work on the same network and communicate with each other to complete an assigned mission."
      ],
      "What is the likely impact?": [
        "The impact of Cloud Computing can be everywhere; it makes changes in the way organizations function:",
        "- On business: Cloud computing allows businesses to manage their resources remotely. It enables business entities to virtually access their information, allowing data to be accessed at any time and from any location. More and more companies are moving towards this technology because of its benefits to the users.",
        "- On Workforce: Cloud computing creates a virtual workplace where several apps and services can be hosted on a single platform. Employees can easily access their work from anywhere in the world at any time, as long as they have access to the Internet. As a result, cloud computing makes working easier and has increased staff productivity. In the future, remote work can be a new trend in businesses.",
        "- On Society: the impacts of Cloud on day-to-day life are in various ways. Social media (E.g. Facebook, Instagram), entertainment (E.g. Netflix, Spotify), shopping (E.g. Amazon, Shopee), education (E.g. Udemy, Linkedin learning) are all using Cloud because of the conveniences it brings not only to the users but also to the service providers. Sooner or later, more and more daily services will have to apply Cloud Computing to their function.",
        "People working in the IT field are the most affected as organizations relocate their networks to Cloud platforms. The needs of some in-house IT jobs like System Administrators, Database Administrators, and Help desk support are predicted to reduce in the future as Cloud can also provide those functions. However, new skills sets and positions will be required as IT jobs migrate from individual organizations to Cloud service providers. Security is a huge issue of Cloud computing, and positions like security architect or security engineer are among the most sought-after jobs. In addition, positions like Cloud administrator, Cloud architect, Cloud engineer play significant roles in building Cloud networks and Cloud management."
      ],
      "How will this affect me?": [
        "The occurrence of Cloud computing has brought to my daily life many conveniences and changes:",
        "- In education: As I was a kid, I used to go directly to the campus or the teacher's house for extra classes; it took me lots of time travelling and sometimes was inconvenient. However, in recent years, there have been more and more online courses via platforms like Udemy, Coursera, Linkedin Learning, and many of them are interesting. I can stay at home and have access to a variety of courses from programming, mathematics to music tutorials, design studies.",
        "- Personal Storage: This was one of the head-aching problems that I usually had to deal with before knowing about Cloud. A phone with just 16Gb of storage was not enough for a person who loves recording videos like me, and I always needed to use a USB for data transferring. After I knew about Cloud, everything became much easier since I could post, literally, all of my works online via Google Drive or Apple iCloud. In addition, I can access my online storage everywhere I go and with different devices.",
        "- Online Shopping: During the CoVid-19 pandemic time, it is safer to stay at home and order stuff online. Most online shopping platforms are using Cloud to manage customers' information to recommend suitable products to give users like me the best user experiences.",
        "- Social impact: The development of social networks like Facebook or Zalo makes it easier for me to keep in touch with my family and friends through the online community.",
        "- Healthcare: Cloud computing helps me and my family members manage and share health data to keep track of the medical record and health problems.",
        "Cloud Computing plays a significant role in our everyday lives, and shortly, there will be more practical applications of it."
      ]
    },
  },
  {
    technology: "Autonomous Vehicle",
    image: "AutoVehicle.png",
    description: {
      "What does it do?": [
        "An autonomous vehicle can sense its surroundings and operate without the need for human intervention. At no point is a human passenger necessary to assume control of the car, nor is a human passenger required to be present in the vehicle at all. A self-driving automobile can go wherever a regular vehicle can and accomplish everything a skilled human driver can do. Self-driving cars are becoming more popular and fully operational than ever before. Although often advertised as driverless cars, there are currently no fully autonomous vehicles legally operating in countries worldwide.",
        "The American Society of Automotive Engineers (SAE) defines six levels of driving automation, ranging from Level 0 (fully manual) to Level 5 (fully automated). These levels have been approved by the US Department of Transportation and are being applied worldwide.",
        "- Level 0 – manual driving: Humans operate and control all major systems. This includes cars with cruise control because the driver sets and changes the speed as needed.",
        "- Level 1 - driver assistance: Advanced driver assistance systems (ADAS) help the driver with steering, braking, and acceleration, but not all simultaneously. A rearview camera and features such as vibrating seat alarms are included in ADAS to notify drivers when they stray from their driving lane. When triggered individually by human drivers, the automobile can control several systems, such as adaptive cruise control or automated braking. As a result, most cars nowadays are self-driving at level 1.",
        '- Level 2 - partial automation: Level 2 takes things a step farther, as one could imagine. The car can be more proactive in managing specific circumstances by integrating two or more advanced driver assistance systems, such as automated lane departure warning, lane maintenance and braking, or changing direction and acceleration. The driver can operate without paying much attention at this level, but they must constantly be "alert" to engage and ready to act.',
        '- Level 3 - conditional automation: The third degree of automaticity, sometimes known as "no need to watch the road" mode, allows the driver to perform other things with their eyes-free, such as glance at a phone or tablet. Level 3 self-driving cars often do not require human intervention at speeds below 60 km/h.',
        '- Level 4 - high automation: Through constant monitoring of road conditions, the automobile may autonomously change course, brake, or accelerate, and even avoid obstacles at level 4. The level 4 self-driving mechanism can only be triggered on excellent roads, guaranteeing that the vehicle can decelerate and stop safely when needed by enabling the driver to rest and sleep if desired.',
        '- Level 5 – full automation: This is the highest level, demonstrating an actual self-driving automobile that can operate autonomously in all scenarios and settings without the need for human involvement. When the car is in motion, drivers may easily rest, sleep, or do anything they like. At this level, the automobile lacks even basic features like a steering wheel, accelerator, and brake pedal. Artificial intelligence is crucial in dealing with circumstances based on data from hundreds of sensors.',
        'Complex technology demands everything from automated to autonomous driving, including advanced sensor technologies, sophisticated control systems, and intelligent actuators. However, it is not just a matter of autonomous cars starting on their own. Safety will remain a primary concern in the future, and passenger comfort will become even more vital.',
        "Driverless cars are no longer the impregnable territory of Ford, Daimler, Toyota, Nissan, etc. but are gradually shifting into the domain of software companies. For driverless car development, software plays the most crucial role. It is likened to the brain, ensuring the operation of the car. If in the past, cars were characterized by engines, transmissions, actuators, steering wheels, gasoline, etc., today, it is like a computer. Software and electricity have replaced the functions of mechanical, human, and fuel factors. A modern car is controlled by 80 to 100 embedded systems; 90% of the car's innovation is now in software, 100% of the car will connect to the Cloud. Technology research on autonomous vehicles is centralized into two main areas: lane detection and object recognition.",
        "- Lane detection: Researchers have been studying this subject for decades. Many premium automobiles include lane detecting systems that have been designed and implemented.",
        '- Object recognition: An essential component of autonomous vehicle systems is object recognition. This technology has recently made significant progress in detecting stationery items such as bicycles, pedestrians, automobiles, traffic signs, and similar objects. It is now progressing to recognizing dynamic things such as vehicles and people moving on the roads.'
      ],
      "What is the likely impact?": [
        "Developing the automobile of the future and the systems architecture that will support it will need extensive long-term collaboration among tech innovators, automakers, telecommunications companies, government agencies, and others. However, automobile technology will still see noteworthy progress in the next three years. With the vastly developing AI technology, vehicles will calculate data from sensors more accurately in different situations. As a result, people will see more and more autonomous cars on the roads of many countries. Autonomous vehicles are indeed the future of transportation. Up to now, in the world, more than 30 companies are investing in the research and development of driverless cars, such as Google, Tesla, Apple, Audi, Nissan, Nvidia, etc. They support this field very strongly. As an electronics manufacturing corporation, Apple recently announced that it has successfully developed self-driving cars by 2024. The race for driverless vehicles still has many technological and technological gaps. 2021 will create an opportunity for legislators and consumers to test the feasibility of applying artificial intelligence in traffic. By 2023, a driver monitoring system will be mandatory on all cars that want to achieve the 5-star Euro NCAP safety certification.",
        "With self-driving car proponents soon circulating, they argue that the technology will reduce car accidents caused by human error. Statistics show that driver error is the leading cause, causing more than 90% of all car crashes, and it is often the errors of driving while drunk, distracted, not moving in the right lane, or not complying with regulations, speed limits, etc. In addition, self-driving cars are expected to reduce traffic jams, as robot cars will be able to travel at higher speeds and closer to other vehicles without obstructing or crashing into them. This will ultimately reduce people's time on the road and save them energy.",
        "When self-driving technology is established, fully autonomous self-driving vehicles will be available, but they might have significant economic implications. Taxi and truck drivers will no longer be required, resulting in many people who are now employed in these positions losing their employment. Trucks on the road without a driver could theoretically operate 24 hours a day, lowering freight expenses. There will be fewer car-truck collisions because there will be no sleepy, distracted, or furious truck drivers behind the wheel.",
      ],
      "How will this affect me?": [
        `Although the automobile is pretty popular nowadays in many developed countries worldwide, this technology has not seemed very practical in Vietnam due to different reasons and challenges. Firstly, many streets in Vietnam still lack road markings or are blurred or covered after a period of use. Secondly, the high traffic density makes the vehicle "embarrassed" because it cannot find a safe distance from other vehicles, especially motorbikes. Thirdly, operating self-driving cars in the situation that Vietnam's traffic is still "chaotic" due to lack of synchronization will bring many risks of loss of traffic safety. Many tests have shown that current self-driving cars are only most suitable when running on highways with open lanes and no obstacles. Even in modern and advanced cities, the operation in urban areas still has many problems. Therefore, I believe that I will not have the chance to experience this technology in my home country soon. Even though it will not affect my daily life, I would be happy to try it out in a foreign country someday. Nevertheless, Vietnam is still developing vastly, so I believe that every Vietnamese person will have their own autonomous car one day.`,
      ]
    },
  },
];

export const projectInfo = {
  overview:
    "Background noises are something that we do not usually care about; however, they surprisingly have a significant impact on our daily lives. With busy urban lifestyles, more and more people find hearing natural and comfortable sounds a great way to relax, relieve stress, and increase productivity. It can be the sound of wind blowing from high on top of mountains, the hum of insects and animals deep into the jungle, and also somewhere we are more familiar, like inside of the coffee shop where we hear people chatting along with the melodies of the songs. That idea, combined with our love of coding and technologies, has inspired us to build a small website where people can enjoy some unique sounds of different places. Moreover, users can adjust relative sound levels to achieve perfectly balanced background noise. We call it “Mix in Sounds” or “MinS”.",
  motivation:
    "According to soundofsleep.com, background sounds that usually contain white noise have been shown to have promising results in improving behaviours and productivity. To be specific, it helps us enhance memories, deepens our meditation, sleep quality as well as improves concentration. MinS is developed to bring people a better quality of life with its pristine soundtracks and beautiful photographs. In addition, this website also provides Pomodoro – a study tracking tool that people can use while studying and Spotify integrations if they want to enjoy some of their favourite songs. Anyone can access the website right on their phones, tablets, or laptops, and it will be available on famous browsers like Google Chrome, Safari, Microsoft Edge, and Firefox.",
  description: [
    "In general, MinS is a simple and easy-to-use website. When we first open up, the whole screen will be covered in black, and the logo will slowly appear. After that, it displays, under the logo, “Welcome to Mix in Sounds”, followed by a short description of the website. Users will then be asked to choose between four locations - Chilling by the Sea, Exploring the Forest, Relaxing in a Coffee Shop, and Working at the office – which is shown in turn. The website will play a demo sound of that place along with beautiful scenery in the background interface for each location.  After choosing the desired location, the website will relocate them to a new page, and more soundtracks will be provided. To be more specific, inside the forest, we can hear the light wind, vibrating trees, insects buzz, campfire, as well as the sounds of animals like birds, snakes, and monkeys. When choosing the seaside option, we can hear waves crashing on the shore, sand crunching underfoot, the sound of seagulls and other coastal birds. If users choose to go to a bustling area like a coffee shop, there will be the sound of people chatting, the barista who prepares the beverage for us, the coffee cup, and the drinking sound. Last but not least is at the office where users can hear the sound of discussion, people moving around, writing, and studying. There are also different kinds of weather used in all locations like rainy, windy, sunny, and snowy. It is crucial that all of the sounds are high quality to provide the best user experience.",
    "In terms of the layout, the header, where the website logo and different locations are located, will lie on top of the window, and users can navigate to other places by clicking on them. The set of sounds will be on the right side of the screen. There will be a control bar for each sound for users to adjust. They can choose the sounds they desire by clicking on the play button and dragging the circle dot to the right for higher volume and the other for lowering. The play button will then be changed into the pause symbol in case users want to stop the sound.",
    "Underneath the sounds control panel, there are four circles with an icon inside, representing the weather mentioned before. Users can hold their mouse on that button, drag it up or down to adjust the volume.",
    "For music lovers, the Spotify player is located on the left side of the window and has some default music chosen by the host. If the users have a premium Spotify account, they can also log in and enjoy the entire length of the songs instead of the 30s each. The sound adjusting bar and playback & skip button are also provided for the users for better adjustment.",
    "Pomodoro is one of the trending education tools to help us keep track of our studies time and work effectively. It will be included on the website and displayed on top of the Spotify player. The default option is 25 minutes of working time, followed by 5 minutes of break. Users could also adjust the desired time by clicking on the “EDIT” button. After that, the interface of the Pomodoro will change, and there will be two arrows up-down for us to choose the desired working time.",
    "If the users are satisfied with the website, they can also support us by clicking on the “Support us” button on the bottom left of the interface. They will then be taken to a page where users can find more information about the creators and send a small donation. On the right side of the donation box is some extra information about the website, including the creators, the releasing date, and our slogan.",
    "The colour and size of every button will change slightly if the users hover their cursor on them. In addition, if they hover on each button, there will be a comment pop-up to provide some additional information about that button. The colour and font shown on the website will depend on the background pictures of different locations. Moreover, we would like to use not too bright colours for the website along with stylish and exquisite fonts.",
  ],
  toolsAndTechnologies:
    "The main technology for building this project is ReactJS. It is utilized for building front-end components, including the sounds control panel, header, Pomodoro section, etc. HTML and CSS will also be used for structuring and styling the project. In addition, Spotify API will be integrated into the website for playing songs and users' logins. For the soundtracks, some sounds would be easy for us to record while others need to be rented from other sources like My Noise – one of the best background noise generators on the internet. To have high resolution and nice-exposure pictures, we can use images from Unsplash – a photo discovery platform for free to use, high-definition photos. In addition, Firebase will be used to store the database, different sound packages, and high-quality pictures. Finally, we will use GitHub and Git for handling version controls and remote repositories.",
  skillsRequired:
    "In order to build this website, it is crucial to be proficient at languages and frameworks for frontend development like HTML, CSS, JavaScript, React.JS library. In addition, getting familiar with Firebase and RestAPI could help us work with the Spotify API and backend server. We also need to know about design principles: the font of the letter, the size, colours, and layout of different components to build a nice-looking interface for the project. Furthermore, being familiar with Git and npm command-line interface (including add, commit, push, and pull commands) and managing remote repositories on GitHub is also required. Last but not least, interpersonal skills and teamwork skills to collaborate with other team members are also essential to have.",
  outcome:
    "We aim to start MinS with a website platform and then transition to a mobile application that can run on both IOS and Android devices. RMIT students will be the first to utilize MinS before it is made available to other Internet users. If this project is successfully deployed, people will have a nice place to relax and enjoy high-quality melodies even if they are in bustling areas of the city. In addition, people can also use MinS while studying to improve concentration and efficiency or while sleeping to have a good relaxation. In the future, we will frequently upgrade MinS with more locations and soundtracks, as well as fix and modify the website according to users' feedback at the same time.",
};
